import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '@/styles/globals.css'

const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => (
  <html lang="pt-br">
    <body
      className={`${roboto.className} antialiased bg-black text-white w-100 h-screen p-2`}
    >
      {children}
    </body>
  </html>
)

export default RootLayout
